name: Manual Hello World

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create dummy directory for caching
        run: mkdir -p node_modules

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-28b48f3

      - name: prime-cache-28b48f3
        run: 'echo "Cache hit status: ${{ steps.cache-step.outputs.cache-hit }}"'

      - name: 24f1001257@ds.study.iitm.ac.in
        run: echo "Hello, world!"
