# Name for your workflow, which will be displayed in the Actions tab
name: Manual Hello World

# This trigger allows the workflow to be run manually from the GitHub UI
on:
  workflow_dispatch:

# Defines the jobs that the workflow will run
jobs:
  test:
    # Specifies the type of virtual machine to run the job on
    runs-on: ubuntu-latest

    # A sequence of tasks to be executed in the job
    steps:
      # A standard first step to check out your repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Your original step
      - name: 24f1001257@ds.study.iitm.ac.in
        run: echo "Hello, world!"
